// ROBOTBUILDER TYPE: Subsystem.

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "subsystems/AlgaeInt.h"
#include <frc/smartdashboard/SmartDashboard.h>
#include <frc/XboxController.h>
#include <rev/SparkMax.h>
#include <frc/PS5Controller.h>

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

AlgaeInt::AlgaeInt(){
    SetName("AlgaeInt");
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SetSubsystem("AlgaeInt");

 
/*
 AddChild("motor", &m_motor);
 m_motor.SetInverted(false);
 */


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void AlgaeInt::Periodic() {
    // Put code here to be run every loop

}

void AlgaeInt::SimulationPeriodic() {
    // This method will be called once per scheduler run when in simulation

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.


void AlgaeInt::CheckInput() {
    frc::PS5Controller PS5C{1};
    
    if (PS5C.GetL2Button()) {
        m_motor.Set(-0.4);
    } else if (PS5C.GetL1Button()){
        m_motor.Set(0.4);
    } else {
        m_motor.Set(0);
    }

}