// ROBOTBUILDER TYPE: Subsystem.

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "subsystems/Vertical.h"
#include <frc/smartdashboard/SmartDashboard.h>
#include <frc/XboxController.h>
#include <frc/PS5Controller.h>

#include <rev/SparkMax.h>

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

Vertical::Vertical(){
    SetName("Vertical");
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SetSubsystem("Vertical");

 
/*
 AddChild("motor", &m_motor);
 m_motor.SetInverted(false);
 */


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Vertical::Periodic() {
    // Put code here to be run every loop

}

void Vertical::SimulationPeriodic() {
    // This method will be called once per scheduler run when in simulation

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.


void Vertical::CheckInput() {
    frc::PS5Controller PS5C{1};
    
    if (PS5C.GetSquareButton()) {
        liftMotor.Set(-1);
    } else if (PS5C.GetTriangleButton()){
        liftMotor.Set(1);
    } else {
        liftMotor.Set(0);
    }

}